# docker-compose.yml
version: "3.8"
services:
  nginx:
    platform: linux/x86_64
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "1234:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src/semesta_energy:/var/www/html/semesta_energy
    networks:
      - app-network
  redis:
    image: redis:4.0
    container_name: app_redis
    ports:
      - "6382:6379"
    networks:
      - app-network
  php:
    platform: linux/x86_64
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src/semesta_energy:/var/www/html/semesta_energy
    working_dir: /var/www/html/semesta_energy
    networks:
      - app-network

  mysql:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '<root-password>'
      MYSQL_DATABASE: "helloworld"
      MYSQL_USER: "helloworld"
      MYSQL_PASSWORD: '<db-password>'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - app-network

  composer:
    platform: linux/x86_64
    container_name: composer
    image: composer/composer
    volumes:
      - ./src/semesta_energy:/var/www/html/semesta_energy
    working_dir: /var/www/html/semesta_energy
    command:
      - install
    networks:
      - app-network
networks:
  app-network:
    driver: "bridge"